EfCoreApp/Controllers/BootcampKayitController.cs
using EfCoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EfCoreApp.Controllers
{
    public class BootcampKayitController : Controller{
        private readonly DataContext _context;

        public BootcampKayitController(DataContext context){
            _context = context;
        }

        public async Task<IActionResult> Index(){
            var bootcampkayitlari = await _context.Kayitlar.Include(x=>x.Ogrenci).Include(x=>x.Bootcamp).ToListAsync();
            return View(bootcampkayitlari);
        }

        public async Task<IActionResult>Create(){
            ViewBag.Ogrenciler = new SelectList(await _context.Ogrenciler.ToListAsync(),"OgrenciId","AdSoyad");
            ViewBag.Bootcamps = new SelectList(await _context.Bootcamps.ToListAsync(),"BootcampId","Baslik");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult>Create(BootcampKayit model){

            model.KayitTarihi = DateTime.Now;
            _context.Kayitlar.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

EfCoreApp/Views/BootcampKayit/Index.cshtml
@model IEnumerable<BootcampKayit>

    <h2>Öğrenci Listesi</h2>
    <a href="BootcampKayit/Create" class="btn btn-primary">Öğrenci Ekle</a>
    <hr>
    <table class="table table-bordered">
        <thead>
            <th style="width: 50px;">@Html.DisplayNameFor(m => m.KayitId)</th>
            <th>@Html.DisplayNameFor(m => m.Ogrenci.AdSoyad)</th>
            <th>@Html.DisplayNameFor(m => m.Bootcamp.Baslik)</th>
            <th style="width: 150px;">Ayarlar</th>
        </thead>
        <tbody>
            @foreach(var item in Model){
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.KayitId)</td>
                    <td>@Html.DisplayFor(modelItem => item.Ogrenci.AdSoyad)</td>
                    <td>@Html.DisplayFor(modelItem => item.Bootcamp.Baslik)</td>
                    <td>
                         <a asp-controller="Ogrenci" asp-action="Edit" asp-route-id="@item.OgrenciId" class="btn btn-primary">Edit</a>
                        <a asp-controller="Ogrenci" asp-action="Delete" asp-route-id="@item.OgrenciId" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

EfCoreApp/Views/BootcampKayit/create.cshtml
@model BootcampKayit

<h2>Bootcamp Kayıt Ekleme</h2>
<hr>
<form asp-controller="BootcampKayit" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="OgrenciId" class="form-label">Öğrenci</label>
        <select asp-for="OgrenciId" asp-items="ViewBag.Ogrenciler" class="form-select">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class="mb-3">
        <label asp-for="BootcampId" class="form-label">Bootcamp</label>
         <select asp-for="BootcampId" asp-items="ViewBag.Bootcamps" class="form-select">
            <option value="">Seçiniz</option>
         </select>
    </div>

    <button type="submit" class="btn btn-primary">Kaydet</button>
</form>