basics/Models/Bootcamp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace basics.Models
{
    public class Bootcamp
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Image { get; set; }
        public string[]? Tags {get;set;}
        public bool isActive {get;set;}
        public bool isHome {get;set;}
    }
}

basics/Models/ErrorViewModel.cs
namespace basics.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

basics/Models/Repository.cs
namespace basics.Models
{
    public class Repository{

        private static readonly List<Bootcamp> _bootcamp = new();

        static Repository(){
            _bootcamp = new List<Bootcamp>(){
                new Bootcamp() {Id = 1, Title = "Backend Bootcamp", Description = "3 hafta sürecek.", Image = "1.jpg", Tags = new string[] {"aspnet","web geliştirme"},isActive=true,isHome=false},
                new Bootcamp() {Id = 2, Title = "Game Bootcamp", Description = "3 hafta sürecek.", Image = "2.jpg", Tags = new string[] {"aspnet","web geliştirme"},isActive=false,isHome=false},
                new Bootcamp() {Id = 3, Title = "Full Stack Bootcamp", Description = "3 hafta sürecek.", Image = "3.jpg", Tags = new string[] {"aspnet","web geliştirme"},isActive=true,isHome=false},
                new Bootcamp() {Id = 4, Title = "React Bootcamp", Description = "3 hafta sürecek.", Image = "1.jpg", Tags = new string[] {"aspnet","web geliştirme"},isActive=true,isHome=true}
            };
        }

        public static List<Bootcamp> Bootcamps{
            get{
                return _bootcamp;
            }
        }

        public static Bootcamp? GetById(int? id){
            return _bootcamp.FirstOrDefault(c=>c.Id == id);
        }
    }
}

basics/Controllers/BootcampController.cs
using basics.Models;
using Microsoft.AspNetCore.Mvc;

namespace basics.Controllers
{
    public class BootcampController : Controller{
        public IActionResult Index(){

            var bootcamp = new Bootcamp();

            bootcamp.Id = 1;
            bootcamp.Title = "Backend Bootcamp";
            bootcamp.Description = "3 hafta sürecek bir bootcamp";
            bootcamp.Image = "1.jpg";
            return View(bootcamp);
        }
        public IActionResult List(){
            return View(Repository.Bootcamps);
        }

        public IActionResult Details(int? id){
            if(id == null){
                return RedirectToAction("List");
            }
            var bootcamp = Repository.GetById(id);
            return View(bootcamp);
        }
    }
} 

basics/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using basics.Models;

namespace basics.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View(Repository.Bootcamps);
    }

    public IActionResult Privacy()
    {
        return View();
    }
}

basics/Views/Shared/_Header.cshtml
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container py-5">
        <h1 class="display-5 fw-bold">Bootcamp Page</h1>
        <p class="col-md-8 fs-4">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloribus rerum maxime accusantium repellendus in autem quasi vero odio, debitis architecto. Magnam blanditiis quia eaque consectetur sint libero harum et reprehenderit.</p>
        <button class="btn btn-success">Detay</button>
    </div>
</div>

basics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <header>
        @await Html.PartialAsync("_Navbar")
        @RenderSection("Header", false)
    </header>
    <div class="container pb-3 mt-3">
        <main>
            @RenderBody()
        </main>
    </div>
    
</body>
</html>

basics/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-dark bg-success">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">BootcampApp</a>
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Bootcamp" asp-action="List" class="nav-link">Bootcamps</a>
                    </li>
                </ul>
            </div>
        </nav>